---

#########################################################
## Set action                                          ##
#########################################################
# If action variable is not defined, gather status of the service
# If service not installed, set action to install. 
# If the service is not started, set action to start.

# Gather installed packages
- name: Gather installed packages...
  ansible.builtin.package_facts:
    manager: auto

# Podman is installed
- name: Detected Podman package...
  when: '"podman" in ansible_facts.packages'
  block:

    # List containers with containers.podman collection
    - name: Gather containers from podman...
      community.general.containers_podman_container_info:
        name: "{{ nexus_repository_container_name }}"
      register: podman_containers   

    # Set action variable to start if container is not running
    - name: Set variable (action)...
      set_fact:
        action_type: "start"
      when: '"Exited" in podman_containers.stdout_lines'

    # Set action variable to install if container is not installed
    - name: Set variable (action)...
      set_fact:
        action_type: "install"
      when: '"{{ nexus_repository_container_name }}" not in podman_containers.stdout_lines'
